import type { FigureSpec, FigPanel, FigSeries } from '../lib/figure';
import { amplitudeAt, cascadeRecords, type CascadeRecord } from '../lib/plots/cascade';
const d=cascadeRecords(), follow=cascadeRecords({scenario:'follow'}), fixed=cascadeRecords({scenario:'fixed'}), um=1e6;
export const P62_VALUES={sub4800:d[6].subHz,sub7200:d[10].subHz,order7200:d[10].subHz/d[10].rotatingHz,follow7200:follow[10].subHz,lockRpm:60*40/.45,lock50Rpm:60*50/.45,oneX:amplitudeAt(d[10].half,120)*um,forward:amplitudeAt(d[10].full,120)*um,backward:amplitudeAt(d[10].full,-120)*um,hold:d.slice(10).map(r=>amplitudeAt(r.half,120)*um)};
const selected=d[10];
export const reading:FigureSpec={id:'fig-p6-2-1',caption:'그림 1. 7200 rpm의 X 변위 FFT입니다. 1X 120 Hz를 먼저 잡고, 2X 240 Hz·1X 아래 40 Hz·비동기 73 Hz·고주파 320 Hz 순서로 위치를 읽습니다. 아래 패널은 같은 기록에 시드 고정 잡음을 더해 바닥을 확대한 것입니다. 줄 하나가 원인 이름은 아닙니다.',panels:[
  {series:[{x:selected.half.freq,y:selected.half.amp.map(a=>a*um),color:'c1'}],x:{range:[0,360],label:'주파수 [Hz]'},y:{range:[0,25],label:'변위 [µm Peak]'},height:220,annotations:[{type:'point',x:120,y:20,label:'① 1X',color:'c1',dy:-14},{type:'point',x:240,y:5,label:'② 2X',dy:-18},{type:'point',x:40,y:12,label:'③ 1X 아래',dy:-18},{type:'point',x:73,y:3,label:'④ 비동기',dy:-15},{type:'point',x:320,y:2,label:'⑤ 고주파',dy:-15}]},
  {title:'⑥ 바닥 보기: 같은 시드 잡음, 세로축 확대',series:[{x:selected.half.freq,y:cascadeRecords({noise:true})[10].half.amp.map(a=>a*um),color:'c4'}],x:{range:[140,180],label:'주파수 [Hz]'},y:{range:[0,.1],label:'[µm Peak]'},height:115},
]};
const stacked=(rows:CascadeRecord[],full=false,time=false):FigPanel=>({height:290,x:{range:[full?-260:0,260],label:'주파수 [Hz]'},y:{range:time?[-2,133]:[1000,8000],label:time?'시각 [s] + 진폭 표시 높이':'회전수 [rpm] + 진폭 표시 높이'},series:rows.map((r,i)=>{const s=full?r.full:r.half, keep=s.freq.map((f,k)=>Math.abs(f)<=260?k:-1).filter(k=>k>=0);return {x:keep.map(k=>s.freq[k]),y:keep.map(k=>(time?r.time:r.rotatingHz*60)+s.amp[k]*um*(time ? 0.25 : 15)),color:i>=10?'c2':'c1',width:1} as FigSeries;})});
export const orderLines:FigureSpec={id:'fig-p6-2-2',caption:'그림 2. 잠김 시나리오의 같은 FFT를 회전수순으로 쌓았습니다. 줄의 가로 위치를 따라가세요. 1X·2X는 회전수와 함께 오른쪽으로, 73 Hz는 같은 자리에 머뭅니다. 세로축은 기록 기준 회전수에 진폭 표시 높이를 더한 것으로 봉우리 꼭대기를 회전수로 읽지 않습니다.',panels:[stacked(d)]};
export const transition:FigureSpec={id:'fig-p6-2-3',caption:'그림 3. FFT 기록에서 읽는 비교 성분의 주파수 경로입니다. 추종만이면 4800→7200 rpm에서 36→54 Hz, 잠김 모델은 36→40 Hz입니다. 처음부터 40 Hz인 줄도 마지막은 40 Hz이므로 앞의 경로와 운전·베어링 정보를 함께 확인합니다. 모드 40 Hz·비율 0.45는 학습값입니다.',panels:[{series:[{x:d.slice(0,11).map(r=>r.rotatingHz*60),y:follow.slice(0,11).map(r=>r.subHz),color:'c1',label:'비율 추종만'},{x:d.slice(0,11).map(r=>r.rotatingHz*60),y:d.slice(0,11).map(r=>r.subHz),color:'c2',label:'추종 → 잠김'},{x:d.slice(0,11).map(r=>r.rotatingHz*60),y:fixed.slice(0,11).map(r=>r.subHz),color:'c3',dash:true,label:'처음부터 고정'}],x:{range:[1200,7200],label:'회전수 [rpm]'},y:{range:[0,60],label:'비교 성분 주파수 [Hz]'},height:225}]};
export const orders:FigureSpec={id:'fig-p6-2-4',caption:'그림 4. 그림 3을 차수로 나누어 읽었습니다. 추종 줄은 0.45X로 일정합니다. 잠긴 40 Hz 줄은 회전수가 높아지면 0.4X(6000 rpm)→0.333X(7200 rpm)로 내려옵니다. 차수 감소는 주파수 감소와 같지 않습니다.',panels:[{series:[{x:d.slice(0,11).map(r=>r.rotatingHz*60),y:d.slice(0,11).map(r=>r.subHz/r.rotatingHz),color:'c2',label:'잠김 모델'},{x:follow.slice(0,11).map(r=>r.rotatingHz*60),y:follow.slice(0,11).map(r=>r.subHz/r.rotatingHz),color:'c1',dash:true,label:'비율 추종만'}],x:{range:[1200,7200],label:'회전수 [rpm]'},y:{range:[0,.6],label:'서브 성분 차수 [X]'},height:180}]};
export const hold:FigureSpec={id:'fig-p6-2-5',caption:'그림 5. 기록 10~12는 모두 7200 rpm, X 1X는 20→25→30 µm Peak입니다. 위 Waterfall은 100·110·120 s 기준선이 나뉘지만 아래 Cascade는 같은 7200 rpm에 겹칩니다. 변화 시각과 수치는 선택 스펙트럼·시간 추세로 확인하세요.',panels:[{...stacked(d.slice(10),false,true),title:'같은 회전수, 다른 시각',x:{range:[110,130],label:'주파수 [Hz]'},y:{range:[95,130],label:'시각 [s] + 진폭 표시 높이'},height:180},{...stacked(d.slice(10)),title:'Cascade 기준선은 모두 7200 rpm',x:{range:[110,130],label:'주파수 [Hz]'},y:{range:[7100,7750],label:'회전수 [rpm] + 진폭 표시 높이'},height:180}]};
export const full:FigureSpec={id:'fig-p6-2-6',caption:'그림 6. X 오른쪽·Y 위쪽·축 반시계 회전의 Full spectrum cascade입니다. 1X는 +와−쪽 모두 회전수를 따라가고, 서브 성분은+쪽에서 추종 후 40 Hz에 잠깁니다. +/−는 선회 방향 분해입니다. 원 반지름을 X 채널 Peak와 같은 값으로 읽지 마세요.',panels:[stacked(d,true)]};
export const split:FigureSpec={id:'fig-p6-2-7',caption:'그림 7. 선택 기록 10(7200 rpm)에서 X 1X는 20 µm Peak, Full spectrum의+1X 반지름은 15·−1X는5 µm입니다. 역방향 몫 50%로 바꾸면 X1X는 20 그대로, 두 반지름은 10/10 µm가 됩니다. 역 성분의 존재 자체가 고장을 확정하지 않습니다.',panels:[{series:[{x:selected.full.freq,y:selected.full.amp.map(a=>a*um),color:'c3'}],x:{range:[-260,260],label:'signed 주파수 [Hz]'},y:{range:[0,20],label:'원 반지름 [µm]'},height:190,annotations:[{type:'point',x:-120,y:5,label:'−1X: 5 µm',dy:-18},{type:'point',x:120,y:15,label:'+1X: 15 µm',dy:-18},{type:'point',x:40,y:12,label:'서브 12 µm',dy:-18}]}]};