import { squareYRange, type FigPanel, type FigSeries, type FigAnnotation, type FigureSpec } from '../lib/figure';
import { orbitRecord, orbitWindow, orbitPoint, idealOneX, type OrbitOptions } from '../lib/plots/orbit';
const um=(v:number)=>v*1e6;
const window=(options:OrbitOptions={},turns=2,start=0)=>orbitWindow(orbitRecord(options),start,turns);
const circle=window(),banana=window({shape:'banana'}),flat=window({shape:'flat'});
const ellipse=window({shape:'ellipse'}),eight=window({shape:'eight'}),loop=window({shape:'loop'}),flower=window({shape:'flower'});
export const P63_VALUES={circleXpp:um(circle.xpp),ellipseYpp:um(ellipse.ypp),bananaX1:um(idealOneX({shape:'banana'}).ax),bananaY1:um(idealOneX({shape:'banana'}).ay),eightY1:um(idealOneX({shape:'eight'}).ay),flatXpp:um(flat.xpp),flatX1:um(idealOneX({shape:'flat'}).ax),halfDots:window({shape:'sub',order:.5},8).distinct,thirdDots:window({shape:'sub',order:1/3},8).distinct,movingDots:window({shape:'sub',order:.43},8).distinct,twoXDots:window({shape:'sub',order:2},8).distinct};
function axes(title:string,series:FigSeries[],annotations:FigAnnotation[]=[],half=110):FigPanel {
  const xr:[number,number]=[-half,half], yr=squareYRange(xr,240); yr[0]=-yr[1]/2;yr[1]=-yr[0];
  return {title,series,annotations,x:{range:xr,label:'X [µm] (좌우를 옮겨 표시)'},y:{range:yr,label:'Y [µm]'},height:240,legend:false};
}
function curve(w:ReturnType<typeof window>,offset=0,color:'c1'|'c2'|'c3'='c1',filtered=false):FigSeries {return {x:(filtered?w.fx:w.x).map(v=>um(v)+offset),y:(filtered?w.fy:w.y).map(um),color};}
function marks(w:ReturnType<typeof window>,offset=0):FigSeries {return {x:w.marks.map(m=>um(m.x)+offset),y:w.marks.map(m=>um(m.y)),color:'text',kind:'dots',radius:4};}
function arrow(w:ReturnType<typeof window>,offset=0,color:'c1'|'c2'='c1'):FigAnnotation {return {type:'arrow',x1:um(w.x[8])+offset,y1:um(w.y[8]),x2:um(w.x[16])+offset,y2:um(w.y[16]),double:false,color};}
const pair=(title:string,a:ReturnType<typeof window>,b:ReturnType<typeof window>)=>axes(title,[curve(a,-75),curve(b,75,'c2'),marks(a,-75),marks(b,75)],[arrow(a,-75),arrow(b,75,'c2')]);
export const measurement:FigureSpec={id:'fig-p6-3-1',caption:'그림 1. 3000 rpm·1X 20 µm Peak의 X/Y를 같은 시각끼리 짝지으면 반지름 20 µm 원이 됩니다. X/Y는 각각 40 µm p-p입니다. 키페이저는 20 ms마다 찍히지만 같은 자리에서 겹칩니다. 평균 축 위치(DC)는 넣지 않았습니다.',panels:[{title:'한 바퀴의 X/Y · 점선은 키페이저 시각',series:[{x:circle.time.map(t=>t*1000),y:circle.x.map(um),color:'c1',label:'X'},{x:circle.time.map(t=>t*1000),y:circle.y.map(um),color:'c2',label:'Y'}],annotations:[{type:'vline',x:0,color:'muted',dash:true},{type:'vline',x:20,color:'muted',dash:true}],x:{range:[0,20],label:'시각 [ms]'},y:{range:[-25,25],label:'AC 변위 [µm]'},height:150}, {...axes('같은 시각의 짝 (동일 축척)',[curve(circle),marks(circle)],[arrow(circle)],80),x:{range:[-80,80],label:'X [µm]'}}]};
export const filterCompare:FigureSpec={id:'fig-p6-3-2',caption:'그림 2. 같은 바나나 예제: X 1X 20, Y 1X 12 + 2X 12 µm Peak. 왼쪽 직접 오빗에는 2X가 섞이고, 오른쪽 실제 1X 트래킹 필터에는 X/Y 약 20/12 µm Peak의 타원이 남습니다. 4초 준비 후·띠 폭 4 Hz이며 작은 필터 잔여는 남습니다. 좌우는 비교를 위해 옮겨 그렸습니다.',panels:[axes('왼쪽: 직접 · 오른쪽: 실제 1X 필터',[curve(banana,-75),curve(banana,75,'c3',true)])]};
function blankCircle(sign:1|-1,offset:number):FigSeries {const points=Array.from({length:124},(_,i)=>orbitPoint(i/128,{sign}));return {x:points.map(p=>um(p.x)+offset),y:points.map(p=>um(p.y)),color:sign===1?'c1':'c2'};}
const reverse=window({sign:-1});
export const marksDirection:FigureSpec={id:'fig-p6-3-3',caption:'그림 3. blank→dot 관례를 지정했습니다. 시간은 빈 구간에서 검은 점으로 들어와 화살표 쪽으로 이어집니다. 왼쪽 반시계는 반시계 자전과 같은 정방향, 오른쪽 시계는 역방향입니다. 두 경우 크기와 점 자리는 같아, 점 위치 하나만으로 방향을 알 수 없습니다.',panels:[axes('시간 순서: 왼쪽 반시계 · 오른쪽 시계',[blankCircle(1,-75),blankCircle(-1,75),marks(circle,-75),marks(reverse,75)],[arrow(circle,-75),arrow(reverse,75,'c2'),{type:'text',x:-51,y:-9,text:'점',anchor:'start'},{type:'text',x:99,y:-9,text:'점',anchor:'start'}]) ]};
export const oneXAndTwoX:FigureSpec={id:'fig-p6-3-4',caption:'그림 4. 위: 원(X/Y 1X 20/20)과 타원(20/10 µm Peak). 아래: Y의 2X 12를 더한 바나나, Y를 2X 20만으로 만든 8자. 원·타원은 1X만으로 만들 수 있고, 이 8자는 Y 1X가 0입니다. 2X가 섞여도 매 축 한 바퀴마다 같은 점이 찍힙니다. 형태는 성분·위상 예제이며 결함을 지정하지 않았습니다.',panels:[pair('왼쪽: 원 · 오른쪽: 타원',circle,ellipse),pair('왼쪽: 바나나 · 오른쪽: 8자',banana,eight)]};
export const complexShapes:FigureSpec={id:'fig-p6-3-5',caption:'그림 5. 왼쪽: 정방향 1X 20 + 1/2X 12 µm의 합은 두 축 바퀴 동안 내부 루프를 만듭니다. 오른쪽: 1X 20 + 3X 8 µm의 합은 꽃잎처럼 찌그러지고, 정방향 3X가 커서 안쪽에 작은 내부 루프 두 개도 생깁니다. 여기서 루프/꽃잎은 합성식의 결과입니다. 접촉이나 유막 불안정의 발생·힘을 계산한 결과가 아닙니다.',panels:[pair('왼쪽: 내부 루프 (두 바퀴) · 오른쪽: 꽃잎',loop,flower)]};
const sub=(order:number)=>window({shape:'sub',order},8);
export const dotCounts:FigureSpec={id:'fig-p6-3-6',caption:'그림 6. 각 패널은 축 8바퀴·펄스 8번입니다. 위 1/2X·1/3X는 각각 2·3자리, 아래 0.43X는 8자리(k = 0과 k = 7은 3.6° 차이로 거의 겹쳐 보임)이고 2X는 1자리입니다. 끝 시각의 중복 펄스는 세지 않았습니다. 0.43X는 매 바퀴 154.8° 이동하며 정확히 43/100X라면 100바퀴 뒤 반복합니다. 점 개수는 표시 구간·성분 구성에 달려 차수 자체가 아닙니다.',panels:[pair('왼쪽: 1/2X (2자리) · 오른쪽: 1/3X (3자리)',sub(.5),sub(1/3)),pair('왼쪽: 0.43X (8자리) · 오른쪽: 2X (1자리)',sub(.43),sub(2))]};
export const flatEvidence:FigureSpec={id:'fig-p6-3-7',caption:'그림 7. 원래 X의 상단을 12 µm에서 자르고 평균을 뺐습니다. 위 파형의 평평한 면이 아래 직접 오빗에도 나타납니다. 직접 X는 32 µm p-p, 실제 1X 필터는 17.15 µm Peak(= 34.3 µm p-p)입니다. 1X 타원이 매끈해져도 원 신호 왜곡은 남습니다. 같은 절단은 접촉과 측정 포화의 원인을 구별해 주지 않습니다.',panels:[{title:'X 직접 파형: 상단 절단 후 AC',series:[{x:flat.time.map(t=>t*1000),y:flat.x.map(um),color:'c1'}],x:{range:[0,20],label:'시각 [ms]'},y:{range:[-25,25],label:'변위 [µm]'},height:140},axes('왼쪽: 직접 · 오른쪽: 실제 1X 필터',[curve(flat,-75),curve(flat,75,'c3',true)])]};