import {it,expect} from 'vitest';
import {bladeModes,bladeFrequency,orderFrequency,bladeCrossing,bladeResponse} from './campbell';
it('교차해를 가진선과 모드선에 독립 대입',()=>{const modes=bladeModes(400,40);for(const m of modes){const s=bladeCrossing(m,12);expect(s.kind).toBe('inside');expect(s.rpm).toBeCloseTo(60*m.frequency0/Math.sqrt(144-m.stiffening),10);expect(bladeFrequency(s.rpm!,m)).toBeCloseTo(orderFrequency(s.rpm!,12),10)}expect(bladeCrossing(modes[0],12).rpm).toBeCloseTo(2353.393621658209,10)});
it('강성화0·rpm 단조·차수에 따른 이동',()=>{const m={frequency0:400,stiffening:40};expect(bladeCrossing({...m,stiffening:0},12).rpm).toBe(2000);expect(bladeFrequency(3000,m)).toBeCloseTo(Math.sqrt(260000),10);expect(bladeFrequency(6000,m)).toBeGreaterThan(bladeFrequency(3000,m));expect(bladeCrossing(m,16).rpm!).toBeLessThan(bladeCrossing(m,12).rpm!)});
it('교차없음·범위밖·끝 경계 포함',()=>{expect(bladeCrossing({frequency0:400,stiffening:144},12).kind).toBe('none');expect(bladeCrossing({frequency0:400,stiffening:145},12).rpm).toBeNull();expect(bladeCrossing({frequency0:700,stiffening:20},8).kind).toBe('outside');expect(bladeCrossing({frequency0:400,stiffening:0},4).kind).toBe('inside');expect(bladeCrossing({frequency0:400,stiffening:0},4,5999).kind).toBe('outside')});
it('감쇠는 교차 위치가 아닌 응답비·위상에 작용',()=>{const m={frequency0:400,stiffening:40},n=bladeCrossing(m,12).rpm!;expect(bladeResponse(n,m,12,.02).amplitudeRatio).toBeCloseTo(25,10);expect(bladeResponse(n,m,12,.08).amplitudeRatio).toBeCloseTo(6.25,10);expect(bladeResponse(n,m,12,.02).phaseLag).toBeCloseTo(Math.PI/2,12);expect(bladeResponse(0,m,12,.02).amplitudeRatio).toBe(1);expect(bladeCrossing(m,12).rpm).toBe(n)});
it('잘못된 파라미터 거부',()=>{for(const m of [{frequency0:0,stiffening:40},{frequency0:400,stiffening:-1}])expect(()=>bladeFrequency(0,m)).toThrow();expect(()=>bladeResponse(0,{frequency0:400,stiffening:40},12,0)).toThrow();expect(()=>orderFrequency(NaN,12)).toThrow();expect(()=>bladeCrossing({frequency0:400,stiffening:40},0)).toThrow()});

it('강성화0의 고주파 극한은 응답0·지연π',()=>{const v=bladeResponse(1e8,{frequency0:400,stiffening:0},12,.02);expect(v.amplitudeRatio).toBeLessThan(1e-8);expect(Math.PI-v.phaseLag).toBeGreaterThan(0);expect(Math.PI-v.phaseLag).toBeLessThan(1e-6)});
